import numpy as np
import re
import matplotlib.pyplot as plt
from numpy import linalg as LA
from matplotlib import cm
import os

plt.style.use('_mpl-gallery')

"""The PES_Filereader function is our function for parsing the input directories, in order it: 
1. Puts all of the files in the directory into a list.
2. Reads the titles to extract theta and r values 
3. Reads each of the files that fit the input file format and extracts the energies using regular expressions 
   (then closes them.)
3. Returns arrays of E, theta, and r"""

def PES_Filereader(Folder): 


    all_files = os.listdir(Folder)

    r_list = []
    theta_list = []
    Energies = []
   
    for name in all_files: 

        if not name.endswith('.out') or name.startswith('.'):
            continue

        r_value = re.search(r'\.r([-+]?\d*\.?\d+)theta', name)
        r_list.append(float(r_value.group(1)))
        

        theta_value = re.search(r'theta([-+]?\d*\.?\d+)\.out', name)
        theta_list.append(float(theta_value.group(1)))
        
        Gaussian_Output = open(f"{Folder}/{name}", 'r')

        #This reads each file but skips up to line 166 for the sake of efficiency. I haven't seen other Gaussian files 
        #so I presume this works for them, but if not it can be removed. 
        for line in Gaussian_Output.readlines()[166:]: 
            match = re.search(r"E\(RHF\)\s*=?\s*([-+]?\d+\.\d+)", line)
            if match: 
                Energies.append(float(match.group(1)))
                break

        Gaussian_Output.close()
    
    #The below code makes sure all of the variables exit the function as arrays. 

    Energies = np.array(Energies) 
    theta_array = np.array(theta_list)
    r_array = np.array(r_list)
    return(Energies, r_array, theta_array)

"""PES_landscaper is the function that generates the potential energy landscape.
As far as I am concerned, this just uses blackbox functions from the matplot lib libraries. 
It doesn't clean up the data extracted at all, just plots it right away. """

def PES_landscaper(Energy, r, theta):

    fig, ax = plt.subplots(subplot_kw={'projection': '3d'}, figsize = (10,7))
    surf = ax.plot_trisurf(r, theta, Energy, cmap=cm.viridis, edgecolor='none', antialiased=True)

    fig.colorbar(surf, ax=ax, shrink=0.5, aspect=5)

    ax.set_xlabel("Bond Length (r) / Å")
    ax.set_ylabel("Bond Angle (Theta) / °")
    ax.set_zlabel("Energies / Hartrees")

    plt.show()


"""PES_Vibrational_Freq is the function that determines the two vibrational frequencies. 
It takes the Energy, r, and theta value arrays generated by the file reading function as inputs and does the following: 
1. Sorts the energies using theta as the primary sort key and r as the second. (Unecessary but adds generality)
2. Determines the unique r and theta values and uses them to determine the step size between r and theta (Step size could be hardcoded but this is general)
   will break if step size isn't even.
3. Reshapes the energies into a 2D array based off of theta and r 
4. Find the energy minimum of the matrix and use the indicies of it to find the equilibrium geometry
5. Uses np.gradient along each axis of the array to find the derivatives with respect to theta and r. 
6. Does 5. again on the new derivitised arrays to find the elements of the hessian matrix. We also mass weight the hessian here.
   The mass weighting here means that we output frequencies as our eigenvalues. 
7. Diagonalises the Mass Weighted Hessian. 
8. Prints the Eigenvalues, they will not print accurately if the bend is of higher frequency than the strech, but as this is rarely applicable I've decided to ignore that.

Methodological notes: 
The frequencies are not completely accurate, this is partially due to errors in the electronic structure calculations though I also think the method I've used could be improved by
fitting a potential curve to my data to generate more points for the hessian matrix. 
I did initally try this, (using a hessian to generate the inital guess for the fit) but I sorely underestimated how much time it would take me. Do you think this would work?"""

def PES_Vibrational_Freq(Energy, r, theta): 

    indices = np.lexsort((r, theta)) 
    sorted_Energy = Energy[indices]

    unique_r = np.unique(r)
    unique_theta = np.unique(theta)

    dr = unique_r[1] - unique_r[0]
    dtheta = unique_theta[1] - unique_theta[0]

    #This defines our mass constants (Hardcoded unfortunately, would have to make a significantly more complex program to find red. masses for non H atoms)
    red_mass_r = 2 * 1.66 * (10 ** (-27))
    red_mass_theta = 0.5 * 1.66 * (10 ** (-27)) 

    #This creates a 2D array of the energies, with r on the x axis and theta on the y axis. 
    E_grid = sorted_Energy.reshape((len(unique_theta),len(unique_r)))

    Equi_row, Equi_coloumn = np.where(E_grid == E_grid.min())

    #Conversion factor constants
    Hartree_to_J = 4.3597447222071 * 10 ** (-18)
    Angstrom_to_m = 1 * 10 ** (-10)
    Degree_to_rad = np.pi / 180
    r_equilibrium = unique_r[Equi_coloumn[0]] * Angstrom_to_m
    moment_inertia = red_mass_theta * r_equilibrium ** 2 
    Speed_of_light_cm = 2.9979 * 10 ** (10)


    #Hessian matrix element calculations    
    theta_grad, r_grad = np.gradient(E_grid, dtheta, dr)
    Second_deriv_of_r = np.gradient(r_grad, dr, axis = 1)[Equi_row, Equi_coloumn] * Hartree_to_J / (red_mass_r * (Angstrom_to_m ** 2))
    Second_deriv_of_theta = np.gradient(theta_grad, dtheta, axis = 0)[Equi_row, Equi_coloumn] * Hartree_to_J / ((Degree_to_rad ** 2) * moment_inertia)
    drdtheta = np.gradient(r_grad, dtheta, axis = 0)[Equi_row, Equi_coloumn] * Hartree_to_J / ((Degree_to_rad * Angstrom_to_m) *np.sqrt(moment_inertia * red_mass_r))
    
    #The creation of the hessian matrix using np.array, and redefinition using .transpose
    Hessian_matrix = np.array([[Second_deriv_of_r, drdtheta],
    [drdtheta, Second_deriv_of_theta]])

    Hessian_matrix = Hessian_matrix.transpose(2, 0, 1)

    eigenvalues, Eigenvectors = LA.eigh(Hessian_matrix)

    kr = eigenvalues[:, 1]
    ktheta = eigenvalues[:, 0]

    Frequency_symmetric = (1 / (2 * np.pi)) * np.sqrt(kr) / (Speed_of_light_cm)
    Frequency_bend = ((1 / (2 * np.pi)) * np.sqrt(ktheta)) / (Speed_of_light_cm)

    print(f"The Symmetric stretch is {Frequency_symmetric[0]} cm⁻¹ and its bending frequency is {Frequency_bend[0]} cm⁻¹")

    



if __name__ == "__main__":
    UserFolder = input("What is the directories filepath?")

    Energies_in, r_in, theta_in = PES_Filereader(UserFolder)

    Type_of_query = input("""Which function should I perform?
        1. Calculate and graph the PES
        2. Calculate the vibrational frequencies
        3. Exit""")

    if Type_of_query == "1": 
        PES_landscaper(Energies_in, r_in,  theta_in)
        exit()
    
    elif Type_of_query == "2": 
        PES_Vibrational_Freq(Energies_in, r_in, theta_in)
        exit()

    elif Type_of_query == "3": 
        exit()